### 通过手机号重置密码
POST {{host}}/{{version}}/auth/password-reset/using-phone
Authorization: Bearer {{token}}

{
    "phone": "{{phone}}",
    "verify_code": "123456",
    "password": "{{password}}"
}

### 通过邮箱重置密码
POST {{host}}/{{version}}/auth/password-reset/using-email
Authorization: Bearer {{token}}

{
    "email": "{{email}}",
    "verify_code": "123456",
    "password": "{{password}}"
}