// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

type CreateUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UpdateUser struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}
