### 使用手机号，短信验证码进行登录
POST {{host}}/v1/auth/login/using-phone

{
    "phone": "{{phone}}",
    "verify_code": "123456"
}

### 使用手机, Email, 用户名 和密码进行登录
POST {{host}}/v1/auth/login/using-password

{
    "login_id": "{{email}}",
    "password": "{{password}}",
    "captcha_id": "DvKMyeobyrJgzZ7oDMRX",
    "captcha_answer": "999033"
}

### Refresh token
POST {{host}}/v1/auth/login/refresh-token
Authorization: Bearer {{token}}
